/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Fallback } from "./Fallback";

export { Fallback__factory } from "./factories/Fallback__factory";
